# Generated by Django 2.2.1 on 2019-06-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroundingMeshProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_current', models.FloatField()),
                ('trip_time', models.FloatField()),
                ('grid_depth', models.FloatField()),
                ('grid_height', models.FloatField()),
                ('grid_width', models.FloatField()),
                ('ground_resistivity', models.FloatField()),
                ('gravel_depth', models.FloatField()),
                ('gravel_resistivity', models.FloatField()),
                ('room_temperature', models.FloatField()),
                ('maximum_temperature', models.FloatField()),
            ],
        ),
    ]
